apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-mcp-gateway.fullname" . }}
  labels:
    {{- include "go-mcp-gateway.labels" . | nindent 4 }}
data:
  config.yaml: |
    proxies:
    {{- range .Values.config.proxies }}
      - pattern: {{ .pattern | quote }}
        target_url: {{ .targetUrl | quote }}
    {{- end }}
