{{- if .Values.redis.enabled }}
{{- $secret_name := printf "%s-redis" (include "go-mcp-gateway.fullname" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret_name }}
  labels:
    {{- include "go-mcp-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
type: Opaque
data:
  {{- if .Values.redis.external.enabled }}
  redis-password: {{ .Values.redis.external.password | b64enc | quote }}
  {{- else if .Values.redis.auth.password }}
  redis-password: {{ .Values.redis.auth.password | b64enc | quote }}
  {{- else }}
  {{- $old_sec := lookup "v1" "Secret" .Release.Namespace $secret_name }}
  {{- if or (not $old_sec) (not $old_sec.data) }}
  redis-password: {{ randAlphaNum 32 | b64enc | quote }}
  {{ else }}
  redis-password: {{ index $old_sec.data "redis-password" }}
  {{- end }}
  {{- end }}
{{- end }}