apiVersion: v1
kind: Secret
metadata:
  name: {{ include "go-mcp-gateway.fullname" . }}
  labels:
    {{- include "go-mcp-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  oauth-google-client-id: {{ .Values.config.oauth.google.clientId | b64enc | quote }}
  oauth-google-client-secret: {{ .Values.config.oauth.google.clientSecret | b64enc | quote }}
